# build the project
# initial commit
tasks:
  - name: Setup maven
    init: mvn install
  - name: Setup Mysql  
    init: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=Pass123$ -d mysql:5.7 && sudo apt install maven && docker exec -it some-mysql  mysql -uroot -pPass123$
  - name: Example of passing an environment variable to a command
    env:
      PRINT_ME: "GitpodID"
    command: echo "$PRINT_ME"  
  - name: Call revpro    
    command: >-
          curl -X POST -H 'Content-type: application/json'
          --data '{"GitpodID":$(GITPOD_WORKSPACE_ID),"GitpodUserName":$(GITPOD_GIT_USER_NAME),"GitpodUserEmail":$(GITPOD_GIT_USER_EMAIL),"time":$(date("Y-m-d H:i:s"))}' https://webhook.site/f4722056-8d9c-4303-bde5-c1d257e2b54c
       
ports:
  - port: 35729
    onOpen: ignore     

